/*  This a source file for SemanticAnalyzer class. It defines every method
    used in analysis if expression generated by Parser is acceptance and correct gramatically.

Copyright (C) 2026 Adam Byczyński.

This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.
    If not, see <https://www.gnu.org/licenses/>.  */


#include "SemanticAnalyzer.h"


SemanticAnalyzer::SemanticAnalyzer(Logger& logger, ProgramExprAST &parsingTree, SymbolTable& symbolTable)
        : logger(logger), parsingTree(parsingTree), symbolTable(symbolTable) {}


void SemanticAnalyzer::performAnalysis() {
    int index = 1;

    for (auto &statementTree: this->parsingTree.statements) {
        this->logger.logMessage(LogSeverity::Info, "Analyzing statement nr. " + std::to_string(index));
        analyzeStatement(statementTree.get());
        index++;
    }
}


void SemanticAnalyzer::analyzeStatement(AbstractExprAST *expr) {
    if (expr == nullptr) {
        this->logger.logMessage(LogSeverity::Error, "Statement analyzed in semantic analyzer is null.");
    }

    if (auto declarationExpr = dynamic_cast<DeclarationExprAST *>(expr)) {
        analyzeDeclarationExpression(declarationExpr);
    } else if (auto assignmentExpr = dynamic_cast<AssignmentExprAST *>(expr)) {
        analyzeAssignmentExpression(assignmentExpr);
    } else if (auto functionPrintValueExpr = dynamic_cast<FunctionPrintValueExprAST *>(expr)) {
        analyzeFunctionPrintValueExpression(functionPrintValueExpr);
    } else if (auto variableReferenceValueExpr = dynamic_cast<VariableReferenceExprAST *>(expr)) {
        analyzeVariableReferenceValueExpression(variableReferenceValueExpr);
    } else if (auto integerExpr = dynamic_cast<IntegerValueExprAST *>(expr)) {
        analyzeIntegerExpression(integerExpr);
    } else if (auto stringExpr = dynamic_cast<StringValueExprAST *>(expr)) {
        analyzeStringExpr(stringExpr);
    } else if (auto floatExpr = dynamic_cast<FloatValueExprAST *>(expr)) {
        analyzeFloatExpr(floatExpr);
    } else if (auto binopExpr = dynamic_cast<BinaryOperatorExprAST *>(expr)) {
        analyzeBinaryOperatorExpression(binopExpr);
    } else if (auto booleanExpr = dynamic_cast<BooleanValueExprAST *>(expr)) {
        analyzeBooleanExpr(booleanExpr);
    } else if (auto whileExpr = dynamic_cast<LoopWhileExprAST *>(expr)) {
        analyzeLoopWhileExpression(whileExpr);
    } else if (auto branchingIfExpr = dynamic_cast<BranchingIfExprAST *>(expr)) {
        analyzeBranchingIfExpression(branchingIfExpr);
    } else if (auto blockExpr = dynamic_cast<BlockExprAST *>(expr)) {
        analyzeBlockExpression(blockExpr);
    } else {
        this->logger.logMessage(LogSeverity::Error, "Semantic Analyzer could not analyze the statement.");
    }
}


std::string SemanticAnalyzer::getPosition(const Token &token) {
    return "[L:" + std::to_string(token.line) + ", C:" + std::to_string(token.column) + "]: ";
}


bool SemanticAnalyzer::isValidVariableIdentifier(const std::string &identifier) {
    std::regex pattern("^[a-zA-Z_][a-zA-Z0-9_]*$");
    return std::regex_match(identifier, pattern);
}

void SemanticAnalyzer::analyzeDeclarationExpression(DeclarationExprAST *expr) {
    // Checking if whole declaration expression is not null
    if (!expr) {
        logger.logMessage(LogSeverity::Error,
            getPosition(expr->getVarNameRefTok()) +
            "Declaration expression is null. Check for incorrect syntax nearby.");
    }

    // Extracting variable declaration information later, needed for analysis and later for Symbol Table
    std::string variableName = expr->getName();
    VariableType variableType = expr->getVariableType();
    VariableScope variableScope = expr->getScope();
    const auto &variableValueExpr = expr->getInitExpression();
    llvm::Value* variableValuePointer = nullptr;

    // Log the general info about declaration
    logger.logMessage(LogSeverity::Info,
        getPosition(expr->getVarNameRefTok()) +
        "Variable Declaration: " + variableName +
        ", Type: " + expr->getTypeInString() + ".");

    // 1. Checking if name is valid
    if (!isValidVariableIdentifier(variableName)) {
        logger.logMessage(LogSeverity::Error,
            getPosition(expr->getVarNameRefTok()) +
            "Invalid variable name \"" + variableName + "\".");
    }

    // 2. Checking if variable with the same name is already declared
    if (symbolTable.isVariableDeclared( variableName, variableScope)) {
        logger.logMessage(LogSeverity::Error,
            getPosition(expr->getVarNameRefTok()) +
            "Variable \"" + variableName + "\" is already declared in current scope.");
    }

    // 4. Check initialization
    if (!variableValueExpr) {
        logger.logMessage(LogSeverity::Error,
            getPosition(expr->getVarNameRefTok()) +
            "Variable \"" + variableName + "\" must be initialized.");
    }

    // 5. Analyze the initialization expression
    try {
        analyzeStatement(variableValueExpr.get());
        } catch (const std::exception& e) {
        logger.logMessage(LogSeverity::Error,
            getPosition(expr->getVarNameRefTok()) +
            "Error in initialization expression: " + e.what());
    }

    // 6. Type checking
    if (!checkIfValueMatchesType(variableType, variableValueExpr)) {
        logger.logMessage(LogSeverity::Error,
            getPosition(expr->getVarNameRefTok()) +
            "Type mismatch: Cannot initialize variable \"" + variableName +
            "\" of type \"" + expr->getTypeInString() +
            "\" with given expression.");
    }


    // 7. Finally, add variable to symbol table
    try {
        symbolTable.declareVariable(variableName, variableType, variableScope, variableValuePointer);
    } catch (const std::exception& e) {
        logger.logMessage(LogSeverity::Error,
            getPosition(expr->getVarNameRefTok()) +
            "Failed to declare variable: " + e.what());
    }
}

void SemanticAnalyzer::analyzeIntegerExpression(IntegerValueExprAST *expr) {
    if (!expr) {
        this->logger.logMessage(LogSeverity::Error, getPosition(expr->getValueRefTok()) + "Invalid integer expression.");
    }

    int value = expr->getValue();
    this->logger.logMessage(LogSeverity::Info, getPosition(expr->getValueRefTok()) + "Found integer: " + std::to_string(value) + "");

    if(value < LLONG_MIN || value > LLONG_MAX){
        this->logger.logMessage(LogSeverity::Error, "Integer value out of range.");
    }
}

void SemanticAnalyzer::analyzeLoopWhileExpression(LoopWhileExprAST *expr) {
    if (!expr) {
        this->logger.logMessage(LogSeverity::Error, getPosition(expr->getConditionRefTok()) + "While statement is null.");
    }

    analyzeStatement(expr->getCondition().get());
    if (!checkIfValueMatchesType(VariableType::BOOL, expr->getCondition())) {
        this->logger.logMessage(LogSeverity::Error, getPosition(expr->getConditionRefTok()) + "While loop condition must evaluate to a boolean.");
    }

    analyzeStatement(expr->getBody().get());
}


void SemanticAnalyzer::analyzeFloatExpr(FloatValueExprAST *expr) {
    if (!expr) {
        this->logger.logMessage(LogSeverity::Error, getPosition(expr->getValueRefTok()) + "The Float Value expression is null.");
    }

    double value = expr->getValue();
    this->logger.logMessage(LogSeverity::Info, getPosition(expr->getValueRefTok()) + "Analyzing float value: " + std::to_string(value) + ".");

    // Check for NaN or Infinity
    if (std::isnan(value)) {
        this->logger.logMessage(LogSeverity::Error, getPosition(expr->getValueRefTok()) + "Float value is NaN.");
    }
    if (std::isinf(value)) {
        this->logger.logMessage(LogSeverity::Error, getPosition(expr->getValueRefTok()) + "Float value is infinite.");
    }

    // Range checks for single precision (float)
    if (value < std::numeric_limits<double>::lowest() || value > std::numeric_limits<double>::max()) {
        this->logger.logMessage(LogSeverity::Error, getPosition(expr->getValueRefTok()) + "Float value out of range.");
    }

    if (value > 0 && value < std::numeric_limits<double>::denorm_min()) {
        this->logger.logMessage(LogSeverity::Error, getPosition(expr->getValueRefTok()) + "Float value is too small (subnormal).");
    }
}


void SemanticAnalyzer::analyzeBooleanExpr(BooleanValueExprAST *expr) {
    if (!expr) {
        this->logger.logMessage(LogSeverity::Error, getPosition(expr->getValueRefTok()) + "Invalid string expression.");
    }
    std::string valueString = std::to_string(expr->getValue());
    this->logger.logMessage(LogSeverity::Info, getPosition(expr->getValueRefTok()) + "Analyzing boolean value: " + valueString + "");
}

void SemanticAnalyzer::analyzeBranchingIfExpression(BranchingIfExprAST *expr) {
    if (!expr) {
        this->logger.logMessage(LogSeverity::Error, getPosition(expr->getConditionRefTok()) + "If statement is null.");
    }

    this->logger.logMessage(LogSeverity::Info, getPosition(expr->getConditionRefTok()) + "Found If statement.");

    analyzeStatement(expr->getCondition().get());
    if (!checkIfValueMatchesType(VariableType::BOOL, expr->getCondition())) {
        this->logger.logMessage(LogSeverity::Error, getPosition(expr->getConditionRefTok()) + "If statement condition must evaluate to a boolean.");
    }

    analyzeStatement(expr->getThenBranchExpr().get());
    if (expr->getElseBranchExpr()) {
        analyzeStatement(expr->getElseBranchExpr().get());
    }

}


void SemanticAnalyzer::analyzeStringExpr(StringValueExprAST *expr) {
    if (!expr) {
        this->logger.logMessage(LogSeverity::Error, getPosition(expr->getValueRefTok()) + "String expression is null.");
    }

    const std::string& value = expr->getStringValue();
    this->logger.logMessage(LogSeverity::Info, getPosition(expr->getValueRefTok()) + "Analyzing string value: \"" + value + "\"");

    if (value.length() > MAX_STRING_LENGTH) {
        this->logger.logMessage(LogSeverity::Error, getPosition(expr->getValueRefTok()) + "String value exceeds maximum length.");
    }
}


void SemanticAnalyzer::analyzeAssignmentExpression(AssignmentExprAST *expr) {
    std::string variableName = expr->getVariableName();
    VariableScope variableScope = expr->getVariableScope();

    this->logger.logMessage(LogSeverity::Info, getPosition(expr->getVariableNameReferenceToken()) + "Analyzing assignment expression for variable " + variableName + "");

    auto symbolInfoOrNull = this->symbolTable.getVariableInfo(variableName);
    if(!symbolInfoOrNull.has_value()) {
        this->logger.logMessage(LogSeverity::Error, getPosition(expr->getVariableNameReferenceToken()) + "Variable \"" + variableName + "\" has not been declared before.");
    }
    VariableType variableType = symbolInfoOrNull.value()->variableType;

    if (!symbolTable.isVariableDeclared(variableName, variableScope)) {
        this->logger.logMessage(LogSeverity::Error, getPosition(expr->getVariableNameReferenceToken()) + "Variable with identifier \"" + variableName + "\" has not been declared. It could also be a type in keyword.");
    }

    this->logger.logMessage(LogSeverity::Info, getPosition(expr->getVariableNameReferenceToken()) + "Variable with identifier \"" + variableName + "\" has been declared.");

    if(!checkIfValueMatchesType(variableType, expr->getNewValue())) {
        std::string variableTypeString = VariableTypeUtils::getStringFromVariableType(variableType).value();
        this->logger.logMessage(LogSeverity::Error,  "Mismatch between variable type " + variableTypeString + " and its value.");
    }
    this->logger.logMessage(LogSeverity::Info, getPosition(expr->getVariableNameReferenceToken()) + "New value of variable " + variableName + " matches its type " + VariableTypeUtils::getStringFromVariableType(variableType).value() + ".");
}


void SemanticAnalyzer::analyzeBinaryOperatorExpression(BinaryOperatorExprAST *expr) {
    if (!expr) {
        this->logger.logMessage(LogSeverity::Error, getPosition(expr->getLHSRefTok()) + "Binary operator expression is null.");
    }

    this->logger.logMessage(LogSeverity::Info,
        getPosition(expr->getLHSRefTok()) + "Found Binary Operator Expression.");

    analyzeStatement(expr->getLHS().get());
    analyzeStatement(expr->getRHS().get());


    auto lhsType = determineExpressionReturnType(expr->getLHS().get());
    auto rhsType = determineExpressionReturnType(expr->getRHS().get());

    BinaryOperatorType opType = expr->getOperator();

    // Validate if both operands are compatible with each other
    if (!areOperandTypesCompatible(opType, lhsType, rhsType)) {
        this->logger.logMessage(
            LogSeverity::Error,
            getPosition(expr->getLHSRefTok()) +
            "Operator '" + BinaryOperatorTypeUtils::getOperatorString(opType) + "' is not compatible with types: " +
            VariableTypeUtils::getStringFromVariableType(lhsType).value() + " and " +
            VariableTypeUtils::getStringFromVariableType(rhsType).value() + "."
        );
    }

    this->logger.logMessage(
        LogSeverity::Info,
        getPosition(expr->getLHSRefTok()) + "Binary operator expression with operator '" + BinaryOperatorTypeUtils::getOperatorString(opType) + "' analyzed successfully."
    );
}


void SemanticAnalyzer::analyzeBlockExpression(BlockExprAST *expr) {
    if (!expr) {
        this->logger.logMessage(LogSeverity::Error,  getPosition(expr->getBlockExprsRefTok()) + "Block expression is null.");
    }

    for (const auto& statement : expr->getExpressions()) {
        analyzeStatement(statement.get());
    }
}


void SemanticAnalyzer::analyzeFunctionPrintValueExpression(FunctionPrintValueExprAST *expr) {
    this->logger.logMessage(LogSeverity::Info, getPosition(expr->getArgumentRefTok()) + "Analyzing function print expression ");

    if(!expr) {
        this->logger.logMessage(LogSeverity::Error, getPosition(expr->getArgumentRefTok()) + "FunctionPrintValue Expression is null.");
    }

    if(!expr->getArgument()) {
        this->logger.logMessage(LogSeverity::Error, getPosition(expr->getArgumentRefTok()) + "Arguments of FunctionPrintValue Expression are null.");
    }

    analyzeStatement(expr->getArgument().get());
}


void SemanticAnalyzer::analyzeVariableReferenceValueExpression(VariableReferenceExprAST *expr) {
    if(!expr) {
        this->logger.logMessage(LogSeverity::Error, getPosition(expr->getValueRefTok()) + "Variable Reference Value expression is null.");
    }

    const std::string& variableName = expr->getReferencedVariableName();
    VariableScope variableScope = expr->getReferencedScope();

    if(!variableName.empty()){
        if(this->symbolTable.isVariableDeclared(variableName, variableScope)){
            this->logger.logMessage(LogSeverity::Info, getPosition(expr->getValueRefTok()) + "Found variable reference for: " + variableName + ".");
        } else {
            this->logger.logMessage(LogSeverity::Error, getPosition(expr->getValueRefTok()) + "Variable \"" + variableName + "\" has not been declared.");
        }
    } else {
        this->logger.logMessage(LogSeverity::Error, getPosition(expr->getValueRefTok()) + "Variable Reference Value expression is null.");
    }
}


bool SemanticAnalyzer::checkIfValueMatchesType(VariableType variableType, const std::unique_ptr<AbstractExprAST> &expr) {
    if (!expr) {
        return false;
    }

    if (dynamic_cast<IntegerValueExprAST*>(expr.get())) {
        return variableType == VariableType::INT;
    }
    else if (dynamic_cast<FloatValueExprAST*>(expr.get())) {
        return variableType == VariableType::FLOAT;
    }
    else if (dynamic_cast<BooleanValueExprAST*>(expr.get())) {
        return variableType == VariableType::BOOL;
    }
    else if (dynamic_cast<StringValueExprAST*>(expr.get())) {
        return variableType == VariableType::STRING;
    }
    else if (auto varRefExpr = dynamic_cast<VariableReferenceExprAST*>(expr.get())) {
        auto variableTypeOrNull = this->symbolTable.getVariableInfo(varRefExpr->getReferencedVariableName());
        if(!variableTypeOrNull.has_value()) {
            this->logger.logMessage(LogSeverity::Error, "Could not referenced variable type because it was not found in Symbol Table.");
        }
        return variableType == variableTypeOrNull.value()->variableType;
    }
    else if (auto binopExpr = dynamic_cast<BinaryOperatorExprAST*>(expr.get())) {
        return variableType == getBinaryOperationReturnType(binopExpr);
    }
    else {
        return false;
    }
}


VariableType SemanticAnalyzer::determineExpressionReturnType(AbstractExprAST* expr) {
    if (dynamic_cast<IntegerValueExprAST*>(expr)) {
        return VariableType::INT;

    } else if (dynamic_cast<FloatValueExprAST*>(expr)) {
        return VariableType::FLOAT;

    } else if (dynamic_cast<BooleanValueExprAST*>(expr)) {
        return VariableType::BOOL;

    } else if (dynamic_cast<StringValueExprAST*>(expr)) {
        return VariableType::STRING;

    } else if (auto varRefExpr = dynamic_cast<VariableReferenceExprAST*>(expr)) {
        auto variableTypeOrNull = this->symbolTable.getVariableInfo(varRefExpr->getReferencedVariableName());
        if(!variableTypeOrNull.has_value()) {
            this->logger.logMessage(LogSeverity::Error, "Could not get type of referenced variable +" + varRefExpr->getReferencedVariableName() + "because it was not found in Symbol Table.");
        }
        return variableTypeOrNull.value()->variableType;

    } else if (auto binopExpr = dynamic_cast<BinaryOperatorExprAST*>(expr)) {
        return getBinaryOperationReturnType(binopExpr);
    }

    this->logger.logMessage(LogSeverity::Error, "Could not determine type of expression.");
}


bool SemanticAnalyzer::areOperandTypesCompatible(BinaryOperatorType opType, VariableType lhsType, VariableType rhsType) {
    if (opType == BinaryOperatorType::ADD || opType == BinaryOperatorType::SUBTRACT ||
        opType == BinaryOperatorType::MULTIPLY || opType == BinaryOperatorType::DIVIDE
        || opType == BinaryOperatorType::DIVIDE_REMAINDER)
    {
            return (lhsType == VariableType::INT || lhsType == VariableType::FLOAT) &&
                   (rhsType == VariableType::INT || rhsType == VariableType::FLOAT);
    }
    else if (opType == BinaryOperatorType::EQUAL || opType == BinaryOperatorType::NOT_EQUAL ||
        opType == BinaryOperatorType::LESS_THAN || opType == BinaryOperatorType::GREATER_THAN)
    {
        return (lhsType == VariableType::INT || lhsType == VariableType::FLOAT) &&
               (rhsType == VariableType::INT || rhsType == VariableType::FLOAT) ||
                (lhsType == VariableType::BOOL && rhsType == VariableType::BOOL);
    }

    return false;
}


VariableType SemanticAnalyzer::getBinaryOperationReturnType(BinaryOperatorExprAST* expr) {
    BinaryOperatorType opType = expr->getOperator();
    VariableType lhsType = determineExpressionReturnType(expr->getLHS().get());
    VariableType rhsType = determineExpressionReturnType(expr->getRHS().get());

    if (!areOperandTypesCompatible(opType, lhsType, rhsType)) {
        this->logger.logMessage(
            LogSeverity::Error,
            getPosition(expr->getLHSRefTok()) +
            " The operands are not compatible with each other.");
    }

    if (opType == BinaryOperatorType::ADD || opType == BinaryOperatorType::SUBTRACT ||
        opType == BinaryOperatorType::MULTIPLY || opType == BinaryOperatorType::DIVIDE ||
        opType == BinaryOperatorType::DIVIDE_REMAINDER)
    {
        // Arithmetic operations
        if ((lhsType == VariableType::INT || lhsType == VariableType::FLOAT) &&
            (rhsType == VariableType::INT || rhsType == VariableType::FLOAT))
        {
            return (lhsType == VariableType::FLOAT || rhsType == VariableType::FLOAT) ? VariableType::FLOAT
                                                                                      : VariableType::INT;
        }
        this->logger.logMessage(
            LogSeverity::Error,
            getPosition(expr->getLHSRefTok())
            + "The operands are not compatible with each other for arithmetic operator.");
    }
    else if (opType == BinaryOperatorType::EQUAL || opType == BinaryOperatorType::NOT_EQUAL ||
             opType == BinaryOperatorType::LESS_THAN || opType == BinaryOperatorType::GREATER_THAN)
    {
        // Comparison operations
        if (lhsType == VariableType::STRING && rhsType == VariableType::STRING) {
            return VariableType::BOOL;
        }
        if ((lhsType == VariableType::INT || lhsType == VariableType::FLOAT || lhsType == VariableType::BOOL) &&
            lhsType == rhsType) {
            return VariableType::BOOL;
        }
        if ((lhsType == VariableType::INT || lhsType == VariableType::FLOAT) &&
            (rhsType == VariableType::INT || rhsType == VariableType::FLOAT)) {
            return VariableType::BOOL;
        }
        this->logger.logMessage(
        LogSeverity::Error,
        getPosition(expr->getLHSRefTok()) +
        "Could not determine boolean return.");
    }

    // Unsupported operator
    this->logger.logMessage(
    LogSeverity::Error,
    getPosition(expr->getLHSRefTok())
    + "Could not determine return type for unsupported operator");
}
