/*
    This is the main expression of the Abstract Syntax Tree.
    It is used as the first node during parsing and then collects
    expression of each statement generated by the Parser.


Copyright (C) 2026 Adam Byczyński.

This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.
    If not, see <https://www.gnu.org/licenses/>.  */


#ifndef THESIS_COMPILER_PROGRAMEXPRAST_H
#define THESIS_COMPILER_PROGRAMEXPRAST_H

#include <vector>
#include <memory>

#include "AbstractExprAST.h"


class ProgramExprAST : public virtual AbstractExprAST {
public:
    std::vector<std::unique_ptr<AbstractExprAST> > statements;

    void addStatement(std::unique_ptr<AbstractExprAST> statement);

private:
    ExpressionType expressionType = ExpressionType::ProgramExpr;
};


#endif //THESIS_COMPILER_PROGRAMEXPRAST_H
