/*
    This is a source file which keeps all methods used to print
    Abstract Syntax Tree generated by Parser.

Copyright (C) 2026 Adam Byczyński.

This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.
    If not, see <https://www.gnu.org/licenses/>.  */


#include "ASTPrinter.h"


void ASTPrinter::printAST(const std::unique_ptr<ProgramExprAST> &programStatements) {
    std::cout << "\n------------------------------\n"
              << "PARSING TREE: \n"
              << "------------------------------\n";
    std::cout << "Parser found " << programStatements->statements.size() << " statements.\n";
    printFullProgram(programStatements, 0);
    std::cout << "------------------------------\n\n";
}


void ASTPrinter::printFullProgram(const std::unique_ptr<ProgramExprAST> &program, int depth) {
    std::cout << "|  \n";
    for (size_t i = 0; i < program->statements.size(); ++i) {
        bool isLast = (i == program->statements.size() - 1);
        printExpression(program->statements[i], depth + 1, isLast);
        if(!isLast) std::cout << "|  \n|  \n";
    }
}

void ASTPrinter::printExpression(const std::unique_ptr<AbstractExprAST> &expr, int depth, bool isLastChild) {
    if (auto declarationExpr = dynamic_cast<DeclarationExprAST*>(expr.get())) {
            printDeclarationExpr(declarationExpr, depth, isLastChild);
        } else if (auto variableReferenceExpr = dynamic_cast<VariableReferenceExprAST*>(expr.get())) {
            printVariableReferenceExpr(variableReferenceExpr, depth, isLastChild);
        } else if (auto functionPrintValueExpr = dynamic_cast<FunctionPrintValueExprAST*>(expr.get())) {
            printFunctionPrintValueExpr(functionPrintValueExpr, depth, isLastChild);
        } else if (auto blockExpr = dynamic_cast<BlockExprAST*>(expr.get())) {
            printBlockExpr(blockExpr, depth, isLastChild);
        } else if (auto branchingIfExpr = dynamic_cast<BranchingIfExprAST*>(expr.get())) {
            printBranchingIfExpr(branchingIfExpr, depth, isLastChild);
        } else if (auto loopWhileExpr = dynamic_cast<LoopWhileExprAST*>(expr.get())) {
            printLoopWhileExpr(loopWhileExpr, depth, isLastChild);
        } else if (auto binaryOperatorExpr = dynamic_cast<BinaryOperatorExprAST*>(expr.get())) {
            printBinaryOperatorExpr(binaryOperatorExpr, depth, isLastChild);
        } else if (auto assignmentExpr = dynamic_cast<AssignmentExprAST*>(expr.get())) {
            printAssignmentExpr(assignmentExpr, depth, isLastChild);
        } else if (auto integerExpr = dynamic_cast<IntegerValueExprAST*>(expr.get())) {
            printIntegerValueExpr(integerExpr, depth, isLastChild);
        } else if (auto stringExpr = dynamic_cast<StringValueExprAST*>(expr.get())) {
            printStringValueExpr(stringExpr, depth, isLastChild);
        } else if (auto floatExpr = dynamic_cast<FloatValueExprAST*>(expr.get())) {
            printFloatValueExpr(floatExpr, depth, isLastChild);
        } else if (auto booleanExpr = dynamic_cast<BooleanValueExprAST*>(expr.get())) {
            printBooleanValueExpr(booleanExpr, depth, isLastChild);
        } else {
            printIndent(depth, isLastChild);
            std::cerr << "[ERROR] Could not print, unsupported expression type.\n";
            exit(1);
        }
}


void ASTPrinter::printIndent(int depth, bool isLastChild) {
    static thread_local std::vector<bool> branchStatus;

    if (depth >= branchStatus.size())
        branchStatus.resize(depth + 1, false);

    branchStatus[depth - 1] = isLastChild;

    for (int i = 1; i < depth; ++i) {
        if (branchStatus[i - 1])
            std::cout << "   ";
        else
            std::cout << "|  ";
    }

    if (depth > 0) {
        if (isLastChild)
            std::cout << "└──";
        else
            std::cout << "├──";
    }
}


void ASTPrinter::printIntegerValueExpr(IntegerValueExprAST *expr, int depth, bool isLastChild) {
    printIndent(depth, isLastChild);
    std::cout << "[" << expr->getID() << ".IntegerExpr]: " << expr->getValue() << "\n";
}


void ASTPrinter::printBinaryOperatorExpr(BinaryOperatorExprAST *expr, int depth, bool isLastChild) {
    printIndent(depth, isLastChild);
    std::cout << "[" << expr-> getID() << ".BinaryOperatorExpr]\n";

    printIndent(depth + 1, false);
    std::cout << "Lhs:\n";
    printExpression(expr->getLHS(), depth + 2, true);

    printIndent(depth + 1, false);
    std::string opString = BinaryOperatorTypeUtils::getBinaryOperatorTypeString(expr->getOperator()).value();
    std::cout << "Operator: " << opString << "\n";

    printIndent(depth + 1, true);
    std::cout << "Rhs:\n";
    printExpression(expr->getRHS(), depth + 2, true);
}


void ASTPrinter::printDeclarationExpr(DeclarationExprAST *expr, int depth, bool isLastChild) {
    printIndent(depth, isLastChild);
    std::cout << "[" << expr-> getID() << ".DeclarationExpr]\n";

    printIndent(depth + 1, false);
    std::cout << "Identifier: " << expr->getName() << "\n";

    printIndent(depth + 1, false);
    std::cout << "Type: " << expr->getTypeInString() << "\n";

    if (expr->getInitExpression()) {
        printIndent(depth + 1, true);
        std::cout << "Value:\n";
        printExpression(expr->getInitExpression(), depth + 2, true);  // Recursive printing
    } else {
        printIndent(depth + 1, true);
        std::cout << "No Value\n";
    }
}


void ASTPrinter::printVariableReferenceExpr(VariableReferenceExprAST *expr, int depth, bool isLastChild) {
    printIndent(depth, isLastChild);
    std::cout << "[" << expr-> getID() << ".VariableReferenceExpr]: " << expr->getReferencedVariableName() << "\n";
}


void ASTPrinter::printFunctionPrintValueExpr(FunctionPrintValueExprAST *expr, int depth, bool isLastChild) {
    printIndent(depth, isLastChild);
    std::cout << "[" << expr-> getID() << ".FunctionPrintValueExpr]:\n";

    printIndent(depth + 1, true);
    std::cout << "Argument:\n";
    printExpression(expr->getArgument(), depth + 2, true);
}


void ASTPrinter::printBlockExpr(BlockExprAST *expr, int depth, bool isLastChild) {
    printIndent(depth, isLastChild);
    std::cout << "[" << expr-> getID() << ".BlockExpr]:\n";

    const auto &expressions = expr->getExpressions();
    for (size_t i = 0; i < expressions.size(); ++i) {
        printExpression(expressions[i], depth + 1, i == expressions.size() - 1);
    }
}


void ASTPrinter::printBranchingIfExpr(BranchingIfExprAST *expr, int depth, bool isLastChild) {
    printIndent(depth, isLastChild);
    std::cout << "[" << expr-> getID() << ".BranchingIfExpr]:\n";

    printIndent(depth + 1, false);
    std::cout << "Condition:\n";
    printExpression(expr->getCondition(), depth + 2, true);

    printIndent(depth + 1, expr->getElseBranchExpr() == nullptr);
    std::cout << "ThenBranch:\n";
    printExpression(expr->getThenBranchExpr(), depth + 2, true);

    if (expr->getElseBranchExpr()) {
        printIndent(depth + 1, true);
        std::cout << "ElseBranch:\n";
        printExpression(expr->getElseBranchExpr(), depth + 2, true);
    }
}


void ASTPrinter::printLoopWhileExpr(LoopWhileExprAST *expr, int depth, bool isLastChild) {
    printIndent(depth, isLastChild);
    std::cout << "[" << expr-> getID() << ".LoopWhileExpr]:\n";

    printIndent(depth + 1, false);
    std::cout << "Condition:\n";
    printExpression(expr->getCondition(), depth + 2, true);

    printIndent(depth + 1, true);
    std::cout << "Body:\n";
    printExpression(expr->getBody(), depth + 2, true);
}


void ASTPrinter::printAssignmentExpr(AssignmentExprAST *expr, int depth, bool isLastChild) {
    printIndent(depth, isLastChild);
    std::cout << "[" << expr-> getID() << ".AssignmentExpr]:\n";

    printIndent(depth + 1, false);
    std::cout << "Variable Indetifier: " << expr->getVariableName() << "\n";

    if (expr->getNewValue()) {
        printIndent(depth + 1, true);
        std::cout << "New Value:\n";
        printExpression(expr->getNewValue(), depth + 2, true);
    } else {
        printIndent(depth + 1, true);
        std::cout << "No Value\n";
    }
}


void ASTPrinter::printStringValueExpr(StringValueExprAST *expr, int depth, bool isLastChild) {
    printIndent(depth, isLastChild);
    std::cout << "[" << expr-> getID() << ".StringExpr]: \"" << expr->getStringValue() << "\"\n";
}


void ASTPrinter::printFloatValueExpr(FloatValueExprAST *expr, int depth, bool isLastChild) {
    printIndent(depth, isLastChild);
    printf("[%d.FloatExpr]:%g\n", expr-> getID(), expr->getValue());
}


void ASTPrinter::printBooleanValueExpr(BooleanValueExprAST *expr, int depth, bool isLastChild) {
    printIndent(depth, isLastChild);
    std::cout << "[" << expr-> getID() << ".BooleanExpr]: " << (expr->getValue() ? "True" : "False") << "\n";
}