/*  This is a source file which keeps all methods used to print
Abstract Syntax Tree generated by Parser.

Copyright (C) 2025 Adam Byczyński.

This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.
    If not, see <https://www.gnu.org/licenses/>.  */


#ifndef THESIS_COMPILER_ASTPRINTER_H
#define THESIS_COMPILER_ASTPRINTER_H

#include <iostream>
#include <memory>
#include <vector>
#include <thread>

#include "../Expressions/AbstractExprAST.h"
#include "../Expressions/KeywordExpressions/BranchingIfExprAST.h"
#include "../Expressions/KeywordExpressions/LoopWhileExprAST.h"
#include "../Expressions/OperationExpressions/AssignmentExprAST.h"
#include "../Expressions/OperationExpressions/BinaryOperatorExprAST.h"
#include "../Expressions/OperationExpressions/DeclarationExprAST.h"
#include "../Expressions/OperationExpressions/FunctionPrintValueExprAST.h"
#include "../Expressions/ProgramExprAST.h"
#include "../Expressions/UtilsExpressions/BlockExprAST.h"
#include "../Expressions/ValueExpressions/BooleanValueExprAST.h"
#include "../Expressions/ValueExpressions/FloatValueExprAST.h"
#include "../Expressions/ValueExpressions/IntegerValueExprAST.h"
#include "../Expressions/ValueExpressions/StringValueExprAST.h"
#include "../Expressions/ValueExpressions/VariableReferenceExprAST.h"


class ASTPrinter {
public:
    void printAST(const std::unique_ptr<ProgramExprAST> &programStatements);

private:
    void printIndent(int depth, bool isLastChild);

    void printFullProgram(const std::unique_ptr<ProgramExprAST> &program, int depth);

    void printAssignmentExpr(AssignmentExprAST *expr, int depth, bool isLastChild);
    void printBinaryOperatorExpr(BinaryOperatorExprAST *expr, int depth, bool isLastChild);
    void printBlockExpr(BlockExprAST *expr, int depth, bool isLastChild);
    void printBooleanValueExpr(BooleanValueExprAST *expr, int depth, bool isLastChild);
    void printBranchingIfExpr(BranchingIfExprAST *expr, int depth, bool isLastChild);
    void printDeclarationExpr(DeclarationExprAST *expr, int depth, bool isLastChild);
    void printExpression(const std::unique_ptr<AbstractExprAST> &expr, int depth, bool isLastChild);
    void printFloatValueExpr(FloatValueExprAST *expr, int depth, bool isLastChild);
    void printFunctionPrintValueExpr(FunctionPrintValueExprAST *expr, int depth, bool isLastChild);
    void printIntegerValueExpr(IntegerValueExprAST *expr, int depth, bool isLastChild);
    void printLoopWhileExpr(LoopWhileExprAST *expr, int depth, bool isLastChild);
    void printStringValueExpr(StringValueExprAST *expr, int depth, bool isLastChild);
    void printVariableReferenceExpr(VariableReferenceExprAST *expr, int depth, bool isLastChild);
};

#endif //THESIS_COMPILER_ASTPRINTER_H
